name: Draw ZMK keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.json"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install keymap-drawer
        run: pip install keymap-drawer

      - name: Draw keymap
        run: |
          keymap draw config/piantor_pro_bt.keymap > piantor_viz.svg

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add piantor_viz.svg
          git commit -m "Update keymap visualization" || exit 0
          git push
